name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VUE_3_BOOKING_FORM }}'
          channelId: live
          projectId: vue-3-booking-form
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
